services:
  app:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=postgres://endoguard:endoguard@db:5432/endoguard
      - SITE=ethnic-performs-lay-chronicle.trycloudflare.com,localhost:8585
      - FORCE_HTTPS=false
      - PEPPER=ea89748b61e2f9f8ed5f3400d43702a829e2f693
      - ENRICHMENT_API=https://api.endoguard.online
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=endoguard
      - POSTGRES_PASSWORD=endoguard
      - POSTGRES_DB=endoguard
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
